name: woke
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: woke
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0.0.0
        with:
          fail-on-error: true
